---
# defaults file for docker-generic

docker_name: Hello-World
docker_image: hello-world

docker_environment_variables:
  PUID: "1000"
  PGID: "1000"
  VERSION: docker
  TZ: America/Chicago

docker_additional_options:
  restart_policy: unless-stopped

watchtower_update: true
