---
# defaults file for docker-generic

docker_name: Hello-World
docker_image: hello-world

watchtower_update: true

docker_environment_variables:
  PUID: "1000"
  PGID: "1000"
  VERSION: docker
  TZ: America/Chicago

docker_additional_options:
  restart_policy: unless-stopped

docker_labels:
  com.centurylinklabs.watchtower.enable: "{{ watchtower_update }}"
